<div style="direction:rtl;text-align:center;font-size:30px;font-weight:bold">
مقدمة موجزة لمكتبة NumPy

<div style="direction:rtl;text-align:right">
أهلا وسهلا بكم في هذه المقدمة الموجزة إلى مكتبة نمباي. تعتبر مكتبة نمباي هي نواة لجميع مهمات تحليل الأعداد والبيانات في البايثون لأنها تحتوي على قائمة كبيرة من العمليات الرياضية والتي يتم أداؤها ليس بدقة عالية فحسب بل بكفاءة متناهية. لن نحتاج إلى الغوص في تفاصيل هذه المكتبة بل سنقوم في هذا الدرس بإلقاء نظرة عامة على أهم أساسياتها والتي ستساعدنا في الدروس القادمة أثناء تحليل البيانات.

<div style="direction:rtl;text-align:right">
تدور فكرة النمباي حول إضافة أنواع جديدة من حاويات البيانات ألا وهي المصفوفات أو ما يسمى بالتمثيل متعدد الأبعاد للأرقام في شكل مصفوفات. سواء كانت مصفوفة أحادية الأبعاد (وهنا تصبح قائمة من الأرقام فحسب)، أو ثنائية الأبعاد (وهنا تصبح أشبه بجدول من الأرقام، لكل رقم صف وعمود)، أو ثلاثية الأبعاد (وهنا يصبح لدينا مكعب الأرقام، لكل عنصر صف وعمود وعمق) أو متعددة الأبعاد. سنستعرض أمثلة المصفوفات أحادية الأبعاد وثنائية الأبعاد في هذا الدرس.

In [0]:
import numpy as np

<div style="direction:rtl;text-align:right">

# إنشاء المصفوفات

<div style="direction:rtl;text-align:right">
كل ما نحتاجه لإنشاء مصفوفة في نمباي هو قائمة بالأرقام كما في المثال التالي:

In [0]:
a = np.array([1, 2, 3], dtype=np.int)

In [0]:
a

array([1, 2, 3])

<div style="direction:rtl;text-align:right">
نلاحظ أن نمباي تقوم تلقائياً بتحويل قائمة الأرقام إلى مصفوفة ذات بعد واحد (وهو ما يسمى بالمتجه أو vector). على الرغم من أن تعريف المتغير dtype اختياري، إلا أن معرفة نوع الأرقام داخل كل مصفوفة مهم جداً في تحليل البيانات. لذلك نختار إحدى أنواع البيانات في نمباي وهو الأرقام الصحيحة.

<div style="direction:rtl;text-align:right">
لمعرفة حجم المصفوفة أو القائمة، تقوم باستخدام الأمر shape. وهنا نلاحظ أن shape ليس أمراً بل هو خاصية معرفة داخل كل مصفوفة بمعنى أننا لا نريد تنفيذ أي مهمات معينة سوى استدعاء القيمة. نرى النتيجة في قوسين وداخلهما فاصلة وهذه تسمى (tuple).    نرى أولاً عدد الصفوف ثم عدد الأعمدة. بما أننا نتعامل مع متجه، فسيتم عرض رقم واحد فقط هو عدد العناصر بالداخل.

In [0]:
a.shape

(3,)

<div style="direction:rtl;text-align:right">
لاستدعاء العناصر بحسب الموقع (أو الترتيب) سنقوم بإضافة رقم الموقع بعد اسم المتغير:

In [0]:
print(a[0])
print(a[1])
print(a[2])

1
2
3


<div style="direction:rtl;text-align:right">
إضافة إلى كذلك وكما نفعل مع القوائم، يمكننا تغيير أي عنصر في المصفوفة بعد استدعاء العنصر.

In [0]:
a[0] = 20 # تغيير قيمة العنصر الأول

In [0]:
a

array([20,  2,  3])

<div style="direction:rtl;text-align:right">
لنعرف الآن مصفوفة أخرى ذات بعدين بحيث يكون فيها صفوف وأعمدة. لعمل ذلك نقوم بعمل نفس الأمر ولكن حجم القائمة سيتغير كما نرى في المثال التالي

In [0]:
b = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], dtype=np.int)

In [0]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

<div style="direction:rtl;text-align:right">
وهنا نرى أن نمباي قامت بإنشاء مصفوفة ثنائية الأبعاد. من حيث الجوهر، لا تميز نمباي بين المصفوفتين أعلاه، حيث يمكننا استدعاء الكثير من الأوامر للتعرف على هاتين المصفوفتين. 

In [0]:
b.shape

(4, 3)

In [0]:
print(b[0, 0]) # item at row 0, column 0
print(b[0, 1]) # item at row 0, column 1
print(b[1, 0]) # item at row 1, column 0

1
2
4


<div style="direction:rtl;text-align:right">
ولكن قبل أن نخوض في تفاصيل استدعاء العناصر، هناك طرق أخرى لإنشاء المصفوفات بحسب القيم التي نود أن نستخدمها. فمثلاً هناك المصفوفة التي تتكون كلها من أصفار

In [0]:
np.zeros((3,5))    # shape is   3 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<div style="direction:rtl;text-align:right">
وهناك المصفوفات المكونة  من رقم 1 فقط

In [0]:
np.ones((3,2))    

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<div style="direction:rtl;text-align:right">
وهناك المصفوفة المكونة من أرقام عشوائية

In [0]:
np.random.random((2,4))

array([[0.48719984, 0.89522172, 0.43402444, 0.27404542],
       [0.89522215, 0.10392662, 0.05671184, 0.74929598]])

<div style="direction:rtl;text-align:right">
وهناك المصفوفة المكونة من سلسلة معرفة من الأرقام باستخدام الأمر  linspace

In [0]:
nums = np.linspace(start=1, stop=100, num=10)  # i.e., 10 numbers, spaced evenly between 1 and 100

In [0]:
nums

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

<div style="direction:rtl;text-align:right">
بعد ذلك يمكننا تحويل قائمة الأرقام هذه إلى مصفوفة مرتبة بعدد من الصفوف والأعمدة. لاحظ أن عدد الصفوف x عدد الأعمدة  يساوي مجموع عناصر القائمة والذي يمكن استدعاءه باستخدام size.

In [0]:
nums_array = nums.reshape((2,5))

In [0]:
nums.size == nums_array.shape[0]*nums_array.shape[1]

True

<div style="direction:rtl;text-align:right">

# استدعاء العناصر

<div style="direction:rtl;text-align:right">
ليس هناك اختلاف كبير حول طريقة الاستدعاء بين المصفوفات والقوائم (والتي سبق أن تعلمناها في مقدمة البايثون). ولكن هذه المرة سنركز بشكل أكبر على ما تقوم به نمباي في الخلفية.

In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [0]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<div style="direction:rtl;text-align:right">
في الأمر التالي، سوف نستدعي الصف 0 و 1 ، ونستدعي الأعمدة 1 و 2. لاحظ أن الرقم الأخير لا يكون مشمولاً في الاستدعاء، بحيث أن 1:3 لا تعني 1, 2 ,3 بل تعني 1, 2 فقط.

In [0]:
b = a[:2, 1:3]

In [0]:
b

array([[2, 3],
       [6, 7]])

<div style="direction:rtl;text-align:right">
هناك مبدأ مهم في الاستدعاء في نمباي ألا وهو أن نمباي حين تستدعي العناصر، فهي تستدعي "صورة" من الأصل وليس نسخة مستقلة، حيث أن أي تعديل في هذه الصورة فهو تعديل في المصفوفة الأصل. فكن حذراً عن تعديل المصفوفات.

In [0]:
a[0, 1]

2

In [0]:
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]

In [0]:
a[0, 1] 

77

In [0]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<div style="direction:rtl;text-align:right">
نلاحظ أن القيمة في مصفوفة a الأصلية تم تعديلها. بسبب طريقة الاستدعاء القائمة على اقتطاع الأصل، لا نسخة منه. لاقتطاع نسخة منه، نقوم بكل بساطة بإضافة الأمر  copy نهاية الاستدعاء

In [0]:
b = a[:2, 1:3].copy()

In [0]:
a[0, 1]

77

In [0]:
b[0, 0] = 10     # b[0, 0] is the same piece of data as a[0, 1]

In [0]:
a[0, 1] 

77

<div style="direction:rtl;text-align:right">
وهنا نرى أن مصفوفة a لم يجر عليها أي تعديل.

<div style="direction:rtl;text-align:right">

# الجمل الشرطية

<div style="direction:rtl;text-align:right">
في كل مراحل تحليل البيانات، نحتاج دائماً للجمل الشرطية لأغراض مختلفة. مثلاً ماهي العناصر التي تزيد قيمتها عن كذا؟ يمكن اكتشاف هذه الأسئلة من خلال استخدام الأدوات الشرطية: < > | & 

<div style="direction:rtl;text-align:right">
بداية، لنعرف مصفوفة مكونة من أرقام منظمة ليسهل مقارنة النتائج.

In [0]:
a = np.linspace(20, -5, 50) # give me a list 50 equally spaced numbers ordered from 20 to -5 

In [0]:
b = a.reshape((10, 5))

In [0]:
b

array([[20.        , 19.48979592, 18.97959184, 18.46938776, 17.95918367],
       [17.44897959, 16.93877551, 16.42857143, 15.91836735, 15.40816327],
       [14.89795918, 14.3877551 , 13.87755102, 13.36734694, 12.85714286],
       [12.34693878, 11.83673469, 11.32653061, 10.81632653, 10.30612245],
       [ 9.79591837,  9.28571429,  8.7755102 ,  8.26530612,  7.75510204],
       [ 7.24489796,  6.73469388,  6.2244898 ,  5.71428571,  5.20408163],
       [ 4.69387755,  4.18367347,  3.67346939,  3.16326531,  2.65306122],
       [ 2.14285714,  1.63265306,  1.12244898,  0.6122449 ,  0.10204082],
       [-0.40816327, -0.91836735, -1.42857143, -1.93877551, -2.44897959],
       [-2.95918367, -3.46938776, -3.97959184, -4.48979592, -5.        ]])

<div style="direction:rtl;text-align:right">
الآن، لنسأل مثلاً ماهي العناصر التي تزيد قيمتها على 0

In [0]:
b > 0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

<div style="direction:rtl;text-align:right">
هذا الامر يعطينا مصفوفة أخرى بنفس الحجم تماماً ولكن عناصرها إما True أو False بحسب موافقتها للشرط من عدمه. ولكن يمكننا استخدام هذه المصفوفة لاستخراج العناصر التي وافقت الشرط.

In [0]:
b[b < 0]

array([-0.40816327, -0.91836735, -1.42857143, -1.93877551, -2.44897959,
       -2.95918367, -3.46938776, -3.97959184, -4.48979592, -5.        ])

<div style="direction:rtl;text-align:right">
لاحظ أن النتيجة أعلاه هي قائمة من الأرقام، ولم تعد مصفوفة بذات الحجم. وجميع الأرقام هي أقل من 0 لأن هذا شرطنا الذي حددناه.

In [0]:
b.mean()

7.5

<div style="direction:rtl;text-align:right">

# العمليات الحسابية

<div style="direction:rtl;text-align:right">
في هذا الدرس، سوف نتحدث عن مختلف العمليات الحسابية والإحصائية التي يمكن أن نجريها على المصفوفات.

<div style="direction:rtl;text-align:right">
لنبدأ بتعريف مصفوفتين: x و y بأرقام صغيرة لنرى كيف تجرى العمليات الحسابية.

In [0]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [0]:
x

array([[1., 2.],
       [3., 4.]])

In [0]:
y

array([[5., 6.],
       [7., 8.]])

In [0]:
x + y  # جمع عناصر المصفوفة الأولى مع العناصر المقابلة للمصفوفة الثانية
#np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

In [0]:
x - y # طرح عناصر المصفوفة الأولى من العناصر المقابلة في المصفوفة الثانية 
# np.substract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [0]:
x * y # ضرب العناصر في المصفوفة الأولى بالعناصر المقابلة في المصفوفة الثانية
#np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

In [0]:
x / y  # قسمة العناصر في المصفوفة الأولى على العناصر المقابلة في المصفوفة الثانية
#np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [0]:
x ** 2 # رفع عناصر المصفوفة إلى أي قوة
#np.power(x, 2)

array([[ 1.,  4.],
       [ 9., 16.]])

In [0]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [0]:
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [0]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [0]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [0]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [0]:
np.dot(x, y) # ضرب المصفوفات بطريقة جبر المصفوفات أو بما يسمى dot product

array([[19., 22.],
       [43., 50.]])

<div style="direction:rtl;text-align:right">
إضافة إلى كل هذه العمليات الحسابية (والتي كما تلاحظ تجرى لكل عنصر على حدة) نستطيع إجراء عمليات على صفوف كاملة أو أعمدة كاملة. في الأوامر التالية، نحتاج إلى كتابة متغير axis وهو البُعد المستخدم للعملية، بحيث أن قيمة 0 تشير إلى إجراء العملية على الصفوف، وقيمة  1 تشير إلى إجراء العملية على الأعمدة.

In [0]:
x

array([[1., 2.],
       [3., 4.]])

In [0]:
x.sum() # sum of all numbers in x

10.0

In [0]:
x.sum(axis=0) # sum of all rows for each columns

array([4., 6.])

In [0]:
x.sum(axis=1) # sum of all columns for each rows

array([3., 7.])

In [0]:
print('Mean of x: ' ,  x.mean())
print('Mean of x per column: ' ,  x.mean(axis=0))
print('Mean of x per row: ' , x.mean(axis=1))
print('Maximum value of of x: ' , x.max())
print('Maximum value of of x per column: ' ,x.max(axis=0))
print('Maximum value of of x per row: ' ,x.max(axis=1))
print('Minimum value of of x: ' , x.min())
print('Minimum value of of x per column: ' ,x.min(axis=0))
print('Minimum value of of x per row: ' , x.min(axis=1))

Mean of x:  2.5
Mean of x per column:  [2. 3.]
Mean of x per row:  [1.5 3.5]
Maximum value of of x:  4.0
Maximum value of of x per column:  [3. 4.]
Maximum value of of x per row:  [2. 4.]
Minimum value of of x:  1.0
Minimum value of of x per column:  [1. 2.]
Minimum value of of x per row:  [1. 3.]


<div style="direction:rtl;text-align:right">
هذه العمليات الأساسية ستكون هي القاعدة الأساسية التي نبني عليها الحسابات في الدروس القادمة. على الرغم من أن بحر النمباي واسع، إلا أن الأوامر والمهارات التي تحتاج للتعامل معها بشكل دوري معدودة جداً. في الدروس القادمة، سنتوسع تدريجياً في التعرف على نمباي وعلى المكتبات الأخرى بما يناسب احتياجنا.